// https://gist.github.com/keeguon/2310008
export const countries = [
  { key: 'Afghanistan', value: 'Afghanistan' },
  { key: 'Albania', value: 'Albania' },
  { key: 'Algeria', value: 'Algeria' },
  { key: 'Argentina', value: 'Argentina' },
  { key: 'Armenia', value: 'Armenia' },
  { key: 'Australia', value: 'Australia' },
  { key: 'Austria', value: 'Austria' },
  { key: 'Belgium', value: 'Belgium' },
  { key: 'Bolivia', value: 'Bolivia' },
  { key: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
  { key: 'Brazil', value: 'Brazil' },
  { key: 'Bulgaria', value: 'Bulgaria' },
  { key: 'Canada', value: 'Canada' },
  { key: 'Chile', value: 'Chile' },
  { key: 'China', value: 'China' },
  { key: 'Colombia', value: 'Colombia' },
  { key: 'Croatia', value: 'Croatia' },
  { key: 'Cuba', value: 'Cuba' },
  { key: 'Cyprus', value: 'Cyprus' },
  { key: 'Czech Republic', value: 'Czech Republic' },
  { key: 'Denmark', value: 'Denmark' },
  { key: 'Egypt', value: 'Egypt' },
  { key: 'Finland', value: 'Finland' },
  { key: 'France', value: 'France' },
  { key: 'Georgia', value: 'Georgia' },
  { key: 'Germany', value: 'Germany' },
  { key: 'Greece', value: 'Greece' },
  { key: 'Hungary', value: 'Hungary' },
  { key: 'Iceland', value: 'Iceland' },
  { key: 'India', value: 'India' },
  { key: 'Indonesia', value: 'Indonesia' },
  { key: 'Iran', value: 'Iran' },
  { key: 'Iraq', value: 'Iraq' },
  { key: 'Ireland', value: 'Ireland' },
  { key: 'Israel', value: 'Israel' },
  { key: 'Italy', value: 'Italy' },
  { key: 'Japan', value: 'Japan' },
  { key: 'Korea, Republic of', value: 'Korea, Republic of' },
  { key: 'Liberia', value: 'Liberia' },
  { key: 'Liechtenstein', value: 'Liechtenstein' },
  { key: 'Lithuania', value: 'Lithuania' },
  { key: 'Luxembourg', value: 'Luxembourg' },
  { key: 'Macedonia', value: 'Macedonia' },
  { key: 'Malta', value: 'Malta' },
  { key: 'Mexico', value: 'Mexico' },
  { key: 'Moldova, Republic of', value: 'Moldova, Republic of' },
  { key: 'Monaco', value: 'Monaco' },
  { key: 'Mongolia', value: 'Mongolia' },
  { key: 'Morocco', value: 'Morocco' },
  { key: 'Netherlands', value: 'Netherlands' },
  { key: 'Norway', value: 'Norway' },
  { key: 'Oman', value: 'Oman' },
  { key: 'Pakistan', value: 'Pakistan' },
  { key: 'Peru', value: 'Peru' },
  { key: 'Philippines', value: 'Philippines' },
  { key: 'Poland', value: 'Poland' },
  { key: 'Portugal', value: 'Portugal' },
  { key: 'Romania', value: 'Romania' },
  { key: 'Russian Federation', value: 'Russian Federation' },
  { key: 'Saudi Arabia', value: 'Saudi Arabia' },
  { key: 'Serbia and Montenegro', value: 'Serbia and Montenegro' },
  { key: 'Slovakia', value: 'Slovakia' },
  { key: 'Slovenia', value: 'Slovenia' },
  { key: 'South Africa', value: 'South Africa' },
  { key: 'Spain', value: 'Spain' },
  { key: 'Sweden', value: 'Sweden' },
  { key: 'Switzerland', value: 'Switzerland' },
  { key: 'Thailand', value: 'Thailand' },
  { key: 'Tunisia', value: 'Tunisia' },
  { key: 'Turkey', value: 'Turkey' },
  { key: 'Ukraine', value: 'Ukraine' },
  { key: 'United Arab Emirates', value: 'United Arab Emirates' },
  { key: 'United Kingdom', value: 'United Kingdom' },
  { key: 'United States', value: 'United States' },
  { key: 'Uruguay', value: 'Uruguay' },
  { key: 'Venezuela', value: 'Venezuela' },
  { key: 'Viet Nam', value: 'Viet Nam' },
  { key: 'Yemen', value: 'Yemen' },
  { key: 'Zambia', value: 'Zambia' },
];
